version: '3.6'

services: 
    mongo:
        image: mongo
        restart: always
        command: --dbpath data/db
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    server:
        depends_on: 
            - mongo
        build: 
            context: ./server
            dockerfile: Dockerfile
        command: npm run start
        volumes: 
            - ./server:/usr/app/server
            - /usr/app/server/node_modules
        ports: 
            - 3001:3001
    
    client: 
        depends_on:
            - server
        build:
            context: ./client
            dockerfile: Dockerfile
        command: npm run start
        volumes:
            - ./client:/usr/app/client
            - /usr/app/client/node_modules
        ports:
            - 3000:3000

        